---
- name: Configuration deployment with CVP
  hosts: cv_servers
  connection: local
  gather_facts: false
  # collections:
    # - arista.avd
  tasks:
    # - name: Upload configlets to support HOSTS configuration
    #   import_role:
    #     name: arista.avd.cvp_configlet_upload
    #   vars:
    #     configlet_directory: 'intended/configs'
    #     file_extension: 'cfg'
    #     configlets_cvp_prefix: 'AVD'
    #     execute_tasks: True
    #     cv_collection: v1
    #   register: cvp_configlet_results

    # - name: "Execute pending tasks on {{ inventory_hostname }}"
    #   arista.cvp.cv_task_v3:
    #     tasks: "{{ cvp_configlet_results.taskIds }}"
    #   when:
    #     - cvp_configlet_results.taskIds | length > 0

# Fabric configuration

    - name: Provision CVP with AVD configuration for Fabric
      import_role:
        name: arista.avd.eos_config_deploy_cvp
      vars:
        container_root: 'ATD_FABRIC'
        configlets_prefix: 'AVD'
        state: present
        execute_tasks: True

    - name: Provision HOSTS containers
      arista.cvp.cv_container_v3:
        topology:
          ATD_FABRIC:
            parentContainerName: Tenant
          ATD_HOSTS:
            parentContainerName: ATD_FABRIC

# HOSTS configuration

    - name: Provision HOSTS configlets
      arista.cvp.cv_configlet_v3:
        configlets: "{{CVP_CONFIGLETS}}"
        state: present
      vars:
        CVP_CONFIGLETS:
          AVD_s1-host1: "{{ lookup('file', '{{inventory_dir}}/intended/configs/s1-host1.cfg') }}"
          AVD_s1-host2: "{{ lookup('file', '{{inventory_dir}}/intended/configs/s1-host2.cfg') }}"
      register: cvp_configlet_results

    - name: "Execute pending tasks on {{ inventory_hostname }}"
      arista.cvp.cv_task_v3:
        tasks: "{{ cvp_configlet_results.taskIds }}"
      when:
        - cvp_configlet_results.taskIds | length > 0

    - name: Provision HOSTS configuration
      arista.cvp.cv_device_v3:
        devices:
          - fqdn: s1-host1
            parentContainerName: ATD_HOSTS
            configlets:
              - AVD_s1-host1
          - fqdn: s1-host2
            parentContainerName: ATD_HOSTS
            configlets:
              - AVD_s1-host2
      register: cvp_devices_results

    - name: "Execute pending tasks on {{ inventory_hostname }}"
      arista.cvp.cv_task_v3:
        tasks: "{{ cvp_devices_results.taskIds }}"
      when:
        - cvp_devices_results.taskIds | length > 0